# Generated by Django 3.2 on 2022-08-11 23:48

from django.db import migrations, models
import utils.code_generator


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.code_generator.generate_code, max_length=8, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
    ]
