# Generated by Django 3.2 on 2022-08-14 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20220812_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAdress', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
