# Generated by Django 3.2 on 2022-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_quanity_product_quantity'),
        ('accounts', '0003_alter_useradress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites_product', to='products.Product', verbose_name='Favorites'),
        ),
    ]
