# Generated by Django 3.2 on 2022-12-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_video_url'),
        ('accounts', '0004_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonenumber',
            name='active',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites_product', to='products.Product', verbose_name='Favorites'),
        ),
    ]
