# Generated by Django 3.2 on 2022-12-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221231_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphonenumber',
            name='active',
        ),
    ]
