# Generated by Django 3.2 on 2022-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userphonenumber_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphonenumber',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
