# Generated by Django 3.2 on 2023-01-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useradress_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussiness', 'Bussiness'), ('Others', 'Others')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussiness', 'Bussiness'), ('Others', 'Others')], max_length=10, verbose_name='Type'),
        ),
    ]
