# Generated by Django 3.2 on 2022-08-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
