# Generated by Django 3.2 on 2022-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='addres_googlemaps',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Google Maps Adress URL'),
        ),
    ]
