# Generated by Django 3.2 on 2022-12-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_company_addres_googlemaps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='addres_googlemaps',
            new_name='address_googlemaps',
        ),
    ]
