# Generated by Django 3.2 on 2022-12-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_addres_googlemaps_company_address_googlemaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
    ]
