# Generated by Django 3.2 on 2022-12-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_company_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adress',
            new_name='address',
        ),
    ]
