# Generated by Django 3.2 on 2022-08-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('sub_title', models.CharField(max_length=150, verbose_name='Sub Title')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Image')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
        ),
    ]
