# Generated by Django 3.2 on 2023-01-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_title_eng_banner_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='title_eng',
        ),
    ]
