# Generated by Django 3.2 on 2023-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_title_banner_title_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title_ar',
            field=models.CharField(default='', max_length=50, verbose_name='Arabic Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_eng',
            field=models.CharField(max_length=50, verbose_name='English Title'),
        ),
    ]
