# Generated by Django 3.2 on 2023-01-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230120_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='title_eng',
            new_name='title_en',
        ),
    ]
