# Generated by Django 3.2 on 2022-08-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartorder_cartorderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderdetail',
            old_name='order',
            new_name='cart',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Completed', 'Completed')], max_length=50, verbose_name='Order Status'),
        ),
    ]
