# Generated by Django 3.2 on 2022-08-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220827_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderdetail',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
