# Generated by Django 3.2 on 2022-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_price_cartorderdetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderdetail',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cartorderdetail',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cartorderdetail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
