# Generated by Django 3.2 on 2022-11-03 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220827_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('from_date', models.DateField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('to_date', models.DateField(default=django.utils.timezone.now, verbose_name='To Date')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
        ),
    ]
