# Generated by Django 3.2 on 2022-11-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
