# Generated by Django 3.2 on 2023-01-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_coupon_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Price',
            new_name='price',
        ),
    ]
