# Generated by Django 3.2 on 2023-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=15, verbose_name='Delivery Fee'),
        ),
    ]
