# Generated by Django 3.2 on 2023-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
