# Generated by Django 3.2 on 2023-01-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(default='', max_length=200, verbose_name='Delivery Location'),
            preserve_default=False,
        ),
    ]
