# Generated by Django 3.2 on 2022-08-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
