# Generated by Django 3.2 on 2022-12-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_quanity_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default='', verbose_name='Video URL'),
            preserve_default=False,
        ),
    ]
