# Generated by Django 3.2 on 2023-01-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='before_discount_price',
            field=models.IntegerField(default=0, verbose_name='Before Discount Price'),
        ),
    ]
